//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public string DisplayName { get; set; }
        public string CompanyName { get; set; }
        public string Age { get; set; }
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
    }
}
