//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBunter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public Nullable<int> RatingTypeId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> Rating1 { get; set; }
        public string Review { get; set; }
        public byte[] Posted { get; set; }
    }
}
